name: Build and Upload Artifact

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Run make
      working-directory: ./beszel
      run: make

    - name: Build Windows binary
      working-directory: ./beszel
      run: |
        mkdir -p build
        CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o ./build/beszel-agent_windows_amd64 -ldflags "-w -s" beszel/cmd/agent

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: beszel-agent-windows
        path: beszel/build/beszel-agent_windows_amd64
        retention-days: 90
